import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from '../_components/Header'
import AuthProvider from '@/_lib/AuthProvider'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Inkland',
	description: 'Generated by create next app',
}

export default async function RootLayout({
	children,
}: {
	children: React.ReactNode
	}) {
	return (
		<AuthProvider>
			<html lang='en'>
				<body className={`${inter.className} bg-slate-50 relative `}>
					
					<Header/>
					<main className='  text-black h-full'>
						{children}
					</main>
				</body>
			</html>
		</AuthProvider>
	)
}
